// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<Match>> searchTeam({
  required String team,
  required Country country,
}) =>
    RustLib.instance.api.crateApiSimpleSearchTeam(team: team, country: country);

Future<List<TopMatch>> fetchTopMatches() =>
    RustLib.instance.api.crateApiSimpleFetchTopMatches();

enum Country { uk, us, fr }

class Match {
  final String teams;
  final String competition;
  final String date;
  final String time;
  final List<String> channels;

  const Match({
    required this.teams,
    required this.competition,
    required this.date,
    required this.time,
    required this.channels,
  });

  @override
  int get hashCode =>
      teams.hashCode ^
      competition.hashCode ^
      date.hashCode ^
      time.hashCode ^
      channels.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Match &&
          runtimeType == other.runtimeType &&
          teams == other.teams &&
          competition == other.competition &&
          date == other.date &&
          time == other.time &&
          channels == other.channels;
}

class TopMatch {
  final String teams;
  final String date;
  final String time;
  final String matchUrl;

  const TopMatch({
    required this.teams,
    required this.date,
    required this.time,
    required this.matchUrl,
  });

  @override
  int get hashCode =>
      teams.hashCode ^ date.hashCode ^ time.hashCode ^ matchUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TopMatch &&
          runtimeType == other.runtimeType &&
          teams == other.teams &&
          date == other.date &&
          time == other.time &&
          matchUrl == other.matchUrl;
}
